version: "3"

services:

  mongo:
    image: mongo
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db

  backend:
    image: akrana2006/backend:v2
    container_name: backend_app
    depends_on:
      - mongo

  frontend:
    image: akrana2006/frontend:v2
    container_name: frontend_app
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo_data:

